"""Optional real-browser acceptance against a dedicated local demo instance.

Requires installed Playwright/Chromium and CYBERSHIELD_BROWSER_PASSWORD.
Creates one fixture-only scan and logs out; never runs an external scan.
"""
import json
import os
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

BASE=os.getenv('CYBERSHIELD_BROWSER_URL', 'http://127.0.0.1:3200').rstrip('/')
PASSWORD=os.environ['CYBERSHIELD_BROWSER_PASSWORD']
OUTPUT=Path(os.getenv('CYBERSHIELD_BROWSER_OUTPUT', '/tmp/cybershield-session-smoke'))
OUTPUT.mkdir(parents=True, exist_ok=True)
checks=[]
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.getenv('CYBERSHIELD_CHROMIUM', '/snap/bin/chromium'), headless=True, args=['--no-sandbox'])
    context=browser.new_context(viewport={'width':1440,'height':1100})
    page=context.new_page()
    page_errors=[]
    page.on('pageerror', lambda error: page_errors.append(str(error)))
    urls=[]
    page.on('request', lambda req: urls.append(req.url))
    page.goto(BASE,wait_until='networkidle',timeout=60000)
    expect(page.get_by_role('button',name='Demo',exact=True)).to_be_disabled()
    assert context.request.get(BASE+'/api/scans').status==401
    checks.append('anonymous scan access rejected; launch disabled')
    page.get_by_role('button',name='Sign In',exact=True).click()
    expect(page.get_by_label('Password',exact=True)).to_have_value('')
    page.get_by_label('Password',exact=True).fill('wrong-password')
    page.get_by_role('dialog').get_by_role('button',name='Login',exact=True).click()
    expect(page.get_by_text('Invalid email or password',exact=True)).to_be_visible()
    page.get_by_label('Password',exact=True).fill(PASSWORD)
    page.get_by_role('dialog').get_by_role('button',name='Login',exact=True).click()
    expect(page.get_by_title('Log out')).to_be_visible(timeout=20000)
    cookies=context.cookies(BASE+'/api')
    cookie=next(c for c in cookies if c['name']=='cybershield_session')
    assert cookie['httpOnly'] and cookie['sameSite']=='Strict'
    assert page.evaluate("localStorage.getItem('cybershield.authToken')") is None
    assert 'cybershield_session' not in page.evaluate('document.cookie')
    checks.append('configured login; blank password; HttpOnly session; no script-readable token')
    page.get_by_text('I have explicit authorization',exact=True).click()
    with page.expect_response(lambda res: res.url==BASE+'/api/scans' and res.request.method=='POST') as created:
        page.get_by_role('button',name='Demo',exact=True).click()
    assert created.value.status==202,created.value.text()
    scan_id=created.value.json()['id']
    expect(page.get_by_text(f'Current scan: {scan_id} · completed',exact=True)).to_be_visible(timeout=90000)
    assert any('/events?' in url for url in urls)
    assert not any('token=' in url for url in urls)
    checks.append('demo scan completed through cookie-authenticated SSE without URL tokens')
    page.get_by_role('button',name='Reports',exact=True).click()
    # Validate the response generated by the actual download click (new tab).
    responses=[]
    context.on('response',lambda res: responses.append(res) if res.url.endswith(f'/api/scans/{scan_id}/report') else None)
    page.get_by_role('button',name='Download PDF').click()
    page.wait_for_timeout(2500)
    assert responses and responses[-1].status==200
    pdf=context.request.get(BASE+f'/api/scans/{scan_id}/report')
    assert pdf.status==200 and pdf.body().startswith(b'%PDF')
    checks.append('PDF button requested authorized report; valid PDF bytes')
    page.screenshot(path=str(OUTPUT / 'session-report.png'),full_page=True)
    page.reload(wait_until='networkidle')
    expect(page.get_by_title('Log out')).to_be_visible()
    expect(page.get_by_text(f'Current scan: {scan_id} · completed',exact=True)).to_be_visible(timeout=15000)
    checks.append('refresh restores verified identity and account-scoped scan')
    csrf=context.request.post(BASE+'/api/v1/auth/logout',headers={'Origin':'https://evil.invalid','X-CyberShield-Request':'1'})
    assert csrf.status==403
    page.get_by_title('Log out').click()
    expect(page.get_by_role('button',name='Sign In',exact=True)).to_be_visible()
    expect(page.get_by_text('No saved scans yet.',exact=True)).to_be_visible()
    assert context.request.get(BASE+'/api/v1/auth/me').status==401
    assert context.request.get(BASE+f'/api/scans/{scan_id}/report',headers={'Authorization':'Bearer '+cookie['value']}).status==401
    checks.append('cross-origin logout rejected; real logout clears UI and revokes report access')
    page.screenshot(path=str(OUTPUT / 'session-logged-out.png'),full_page=True)
    assert not page_errors,page_errors
    browser.close()
(OUTPUT / 'browser-results.json').write_text(json.dumps({'checks':checks,'page_errors':page_errors},indent=2))
print(json.dumps({'passed':len(checks),'checks':checks,'page_errors':page_errors},indent=2))
